language: php
php:
    - 5.3
    - 5.4

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --quiet --dev

script: "vendor/bin/phpunit --bootstrap=tests/bootstrap.php tests/"
